### ISSUE TITLE
Write Usaybia API connector for VS Code plugin

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#102]
As discussed in #98 

Model: https://github.com/eeditiones/tei-publisher-vscode/blob/master/src/connectors/gnd.ts

Waiting on: #101 and https://github.com/usaybia/srophe-eXist-app/issues/75

This issue could be transferred to the new repo once it's created.

**Comment by wsalesky** [comment]
@nathangibson Okay, here is the first pass. You may end up needing more information passed from the api in order to differentiate between persons/places. 

https://github.com/usaybia/tei-publisher-vscode

The easiest way to test this is to download the .vsix file and install it. (From the extensions tab, there is an option to install from VISX)

**Comment by nathangibson** [comment]
This is AMAZING!! I'm totally geeking out. So far it's working awesome. Can't wait to show it to the team!

If there are tweaks I'll file them in that repo.

**Comment by nathangibson** [comment]
It's also incredibly fast.
