### ISSUE TITLE
Questions for lines in Transkribus

### ISSUE THREAD

**Issue by MalindaT** [usaybia/usaybia-data#17]
On some pages there are these sinces  which are no catch words, right? (I mean the تبقات في and the number. its on p. 40).  How do I tag them? 

![image](https://user-images.githubusercontent.com/46726275/67683136-16d2d200-f991-11e9-8d88-ac0e7b11cb4e.png)

2. If there are gaps between the lines it is till one line, right? Because it is on the same height. Here is an example of what I mean.  (On page 41) 

![image](https://user-images.githubusercontent.com/46726275/67683514-d031a780-f991-11e9-8558-38484a99f1e0.png)

3. On page 47 are the headers not in seperated text regions, but all in one. Shall I always make as much text regions as headers are existing?

![image](https://user-images.githubusercontent.com/46726275/67685293-1a685800-f995-11e9-97bf-ffe25b1cdf63.png)

**Comment by nathangibson** [comment]
Sorry @MalindaT I just got back today. 

Regarding 1., that is fascinating! These are actually quire numbers. (A quire is a group of paper sheets folded together.) This book has sets of 4 sheets folded in half, so you'll see them every 8 pages starting on image 9. It's interesting because you see that a lot on manuscripts but not printed books. 

I created a new structure tag called "quire-number" and I used it on image 9. You can tag it with that.

**Comment by nathangibson** [comment]
>   2. If there are gaps between the lines it is till one line, right? Because it is on the same height.

Yes, these are the same line.
