### ISSUE TITLE
Create factoids for 14.47–14.58

### ISSUE THREAD

**Issue by nathangibson** [usaybia/usaybia-data#180]
@MalindaT The section 14.47–14.58 looks like a good one to do since many of these are people IAU personally met. (@lunadine have you done or are you planning to do any of these?) 

I would suggest starting from the last biography and working backwards, starting with 14.58. Remember, we don't need to record everything in factoids. We are especially interested in the following for any of the people mentioned:
- interactions (personal or written) between people
- relationships between people (teaching, employment, family, servants)
- date and place of birth/death
- places lived or visited
- occupations

@lunadine Do you think of anything I missed or anything to add?
@MalindaT Any questions?

**Comment by MalindaT** [comment]
Hey I have a question concerning chapter 14.49 (Abū Sulaymān Dāwūd ibn Abī l-Munā ibn Abī Fānah with the URI https://usaybia.net/person/356)
In paragraph 14.49.2 it says the following words: 

The ḥakīm Rashīd al-Dīn Abū Ḥulayqah ibn al-Fāris – al-Fāris being the son of the aforementioned Abū Sulaymān Dāwūd – related to me (Ibn Abī Uṣaybiʿah) the following story about his grandfather, Abū Sulaymān Dāwūd, which he said he had heard from the emir Majd al-Dīn, the brother of the jurist (al-faqīh) ʿĪsā, when Majd al-Dīn was talking to the sultan al-Malik al-Kāmil in Shirimsāḥ while visiting him following the death of al-Malik al-ʿĀdil and after the assault of the Franks on the fortress of Damietta. This is what he said, verbatim:....


First I was confused who is talking to UIA but Nadine helped me. But when I searched again in Usaybiah I found several URI's for the son of Abu Sulayman 

https://usaybia.net/person/257 (in Usaybiah it says its the son of Abu Sulayman Dawud)

https://usaybia.net/person/1911 (different name for the same person I guess) 

here is the chapter 14.45: https://scholarlyeditions.brill.com/reader/urn:cts:arabicLit:0668IbnAbiUsaibia.Tabaqatalatibba.lhom-tr-eng1:14.54

**Comment by nathangibson** [comment]
@MalindaT It's a good question because sometimes we do have duplicates. But in this case ...

https://usaybia.net/person/1911 is Rashīd al-Dīn Abū Ḥulayqah, the son of Ibn al-Fāris
https://usaybia.net/person/257 is al-Fāris
https://usaybia.net/person/356 is Abū Sulaymān, the father of al-Fāris

Or am I missing something?

**Comment by lunadine** [comment]
@nathangibson are you sure about person1911?
The way I understood the passage was as follows:

https://usaybia.net/person/1911 is Rashīd al-Dīn Abū Ḥulayqah = Ibn al-Faris = the son of al-Faris
https://usaybia.net/person/257 = al-Fāris
https://usaybia.net/person/356 is Abū Sulaymān = the father of al-Faris = the grandfather of Ibn al-Faris

Or in other words: #356 is father of #257 is father of #1911

@MalindaT  where/how did you find several URI's for the son of Abu Sulayman, is this info from our index? When taking a look at the webpage, I think I don't see a problem, since #1911 is in my understanding the grandfather (note that you need to take the entire name into consideration, not only the "Ibn Abi Sulayman" in the last half, but "Ibn al-Faris Ibn Abi Sulayman" (i.e. to be read as: the son of al-Faris, al-Faris who is the son of Abu Sulayman) . But maybe I am confused myself

**Comment by nathangibson** [comment]
We can discuss this today.

**Comment by nathangibson** [comment]
@lunadine I think you and I are saying the same thing.
