### ISSUE TITLE
Further Steps for Efficient Factoid Creation

### ISSUE THREAD

**Issue by lunadine** [usaybia/usaybia-data#65]
I thought it might be useful to collect some tasks and ideas here, 
for now:

1) See template #55 for faster encoding
2) Semi-automated factoid finding/creation possible? I am thinking of a system where simple relationship-factoids are created based on keywords like "student of" which allows us to simply proofread a number of factoids? (Otherwise I believe we already started something similar in #55 which allows for faster relationship factoid creation). Maybe a very reduced taxanomy might be useful for something like this? 
3) How do we deal with the index-relations? We keep them as some big data-pool in the background or would we like to make more use of it / check how accurate it is for certain chapters and correct it?
4) I remember you already mentioned that you would like to focus on the latest chapters (does this mean we only include factoids for some of the chapters, or rather: we encode more specific factoids only for the later chapters?)
Here is again my diagram from the presentation:
for my purposes I am thinking of excluding (8. Syriac Phyiscans, 12. India and 13. al-Andalus - appart from few specific examples that I might need) 

![grafik](https://user-images.githubusercontent.com/50455791/101328661-94456300-3870-11eb-8405-56afd5892674.png)

5) If you are already working on methods for factoid creation for on religious affiliations, feel free to share your ideas it might also be helpful and give me some further ideas for my own approach.

**Comment by nathangibson** [comment]
Thanks @lunadine . We can keep this issue open for tracking and linking various sub-issues. Here are some preliminary thoughts.
> 
>     1. See template #55 for faster encoding

Yes, this is scheduled for our January release. 
> 
>     2. Semi-automated factoid finding/creation possible? I am thinking of a system where simple relationship-factoids are created based on keywords like "student of" which allows us to simply proofread a number of factoids? (Otherwise I believe we already started something similar in #55 which allows for faster relationship factoid creation). Maybe a very reduced taxanomy might be useful for something like this?

Agreed, I want to create a list of regex expressions we can use to automatically tag relationship keywords in the text with certain taxonomy terms (see #48). Then we could use this as part of #55 code templates to quickly create relation factoids by selecting the people and relationship keywords. 

If you think of a more automated way to do this, I'm open to suggestions, but I haven't thought of a way without producing a lot of erroneous factoids. 

>     3. How do we deal with the index-relations? We keep them as some big data-pool in the background or would we like to make more use of it / check how accurate it is for certain chapters and correct it?

We won't be making factoids for these (since they're not directly from our primary source), but I think we will probably have one or more TEI documents where we collect a big list of `tei:relation`s. We have a preliminary list for testing purposes here https://github.com/usaybia/usaybia-data/blob/development/data/networks/index-relations.xml but we'll need to add real taxonomy terms to this. 

We also need to manually check the index relations.

>     4. I remember you already mentioned that you would like to focus on the latest chapters (does this mean we only include factoids for some of the chapters, or rather: we encode more specific factoids only for the later chapters?)

We will probably be doing automated tagging for all chapters, but we will manually check the tagging and create factoids only for a few chapters. We'll need to decide precisely in the coming months, but my preliminary thoughts are:
 - 14 & 15 are highest priority, since they are where IAU reports most on his own networks.
 - 10 & 11 are also valuable

>     1. If you are already working on methods for factoid creation for on religious affiliations, feel free to share your ideas it might also be helpful and give me some further ideas for my own approach.

I'm working on this for my paper. Some of the affiliational "signals" are already captured in existing factoid formats, like occupations and names. But we will also need something for when affilation is explicitly mentioned. Perhaps using the [state](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-state.html) element. (The TEI elements affiliation and faith are both problematic semantically.)

**Comment by nathangibson** [comment]
@lunadine If you update from your branch, you'll see I've added a bunch of abbreviations for factoids. If you have the usabia-data.code-workspace open, you can just open any XML file, type help and then the TAB button and you'll get a list of some of the most useful ones.

**Comment by nathangibson** [comment]
@lunadine I've also written some documentation here: https://github.com/usaybia/usaybia-data/blob/branch.nadine/.emmet/README.md 

You can use the snippet `help` (type "help" and press TAB) to get a quick list of common snippets.

**Comment by nathangibson** [comment]
@lunadine I think the more specific issues I've mentioned/created above now address the various points mentioned here, so I'll close this issue. 
Also the VSC/Emmet snippets (see above commits) help take care of this.
