### ISSUE TITLE
Linebreaks for Transkribus

### ISSUE THREAD

**Issue by MalindaT** [usaybia/usaybia-data#7]
Dear all, 
it is somehow not possible to add a baseline in Transkribus on page123 l. 1-5. Unfortunately I dont know why. 

Also I want to ask whether to keep everything in one line at page 129 (الكامل at line 2-25) or seperate the poetic meter key in a line on its own.  At line 2-16 on the same page is a name in braces (نحم الدين) is this also supposed to be in the line or create a new one (and then mark it as heading)? Same goes for page 127 at line 2-20. And at least I found a strange linebreak at page 130 l. 5-6.

**Comment by nathangibson** [comment]
@MalindaT I was able to add a line using the process here: https://github.com/usaybia/usaybia-data/issues/3#issuecomment-510842581. However, it did not copy the text to that line, I think because the text is already linked to a strange additional line next to the poetic meter key. In this case I would suggest deleting that extra shape/line (without deleting the parent line text) and then moving the text to the correct line. Does that work for you? If this still doesn't work, maybe check if you have the correct version of Transkribus?

**Comment by nathangibson** [comment]
For page 129 line 2-25, I would separate the poetic meter key, for consistency, since this is what we've done elsewhere, right?

**Comment by nathangibson** [comment]
All names in those special parentheses at the beginning of a paragraph (like 129 2-16 and 127 2-20) are headings. Please split them into a separate line and tag the line as a heading. 

@lunadine Are both of you including or not including the parentheses as part of the heading? For example "نجم الدين بن المنفاخ" or "(نجم الدين بن المنفاخ)"? Either way is fine but it should be consistent. 

On page 130 it is a different case -- the name just has regular parentheses and it is in the middle of a sentence. I think it is just in parentheses as a cross-reference, to show that this person has an entry (on the next page). I have merged the lines in that case--it is not a heading.

**Comment by lunadine** [comment]
I am currently adding parentheses wherever they are missing.

I have another question: we have been inconsistant in the use of final ي and Alif with Hamza أ ; I tried to stick to the text and write فى instead of  في and added the hamza whereas Malinda used the grammatically correct form with final ya. This begs the question should we addapt one system for all pages (probably better?) or do we ignore it?

**Comment by MalindaT** [comment]
I guess it would be better to keep it in one system I can do this today. 

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., Juli 17, 2019 at 11:18 schrieb lunadine<notifications@github.com>:   
I am currently adding parentheses wherever they are missing.

I have another question: we have been inconsistant in the use of final ي and Alif with Hamza أ ; I tried to stick to the text and write فى instead of في and added the hamza whereas Malinda used the grammatically correct form with final ya. This begs the question should we addapt one system for all pages (probably better?) or do we ignore it?

**Comment by lunadine** [comment]
Thank you Malinda, but don't spend too much time on it, I can help you

@nathangibson Maybe I am a bit stupid.. but I don't have a tag titled "heading". This is why I chose the tag "person"

**Comment by nathangibson** [comment]
You are right, it is better to keep the ا and ي consistent and match exactly what is in the book.

@lunadine I might have forgotten to explain the "heading" to you. There are two types of tags in Transkribus. You can use some for any selected text, like "person." Others are only for entire lines (called "structure types"). Headings are structure types. 

We shouldn't use headings for all person names -- only for the ones that begin an entry, the ones in special parentheses at the beginning of a paragraph. The reason for tagging these headings is so that later we can have a table of contents that lists all of the entries. 

There are few of these in your section, so it won't take much work. 

If there is other text on the same line as the heading/name, you have to first click the line on the image and split it using the scissor V button. Then you'll have to open the "Layout" tab in the left sidebar and drag the first of the lines you split below the second (this is because it is right-to-left instead of left-to-right). Both lines will have the same text, so you have to delete the duplicate text. And finally right-click on the line for the name on the page image > Add structure type > heading. See screenshots below. 

Examples:

- I just did this for pg. 127 2-33.
- Pg. 127 2-20 the text is already split but the line on the image is not split and it isn't a heading. You can use a similar process to fix that. 
- Pg. 123 1-15 The text line is not split, and there is only one line on the page image, for the name. You can fix this by adding a new baseline ("+BL" button, draw from left to right) underneath the rest of the text.

I hope this makes sense.

<img width="898" alt="Screen Shot 2019-07-17 at 1 18 07 PM" src="https://user-images.githubusercontent.com/3083452/61372327-1fe2dc00-a897-11e9-9dd5-748f3d57c8e9.png">
<img width="898" alt="Screen Shot 2019-07-17 at 1 18 51 PM" src="https://user-images.githubusercontent.com/3083452/61372334-22453600-a897-11e9-83fe-78e41df0c161.png">
<img width="442" alt="Screen Shot 2019-07-17 at 1 20 37 PM" src="https://user-images.githubusercontent.com/3083452/61372338-25d8bd00-a897-11e9-9a2e-d457ba8ad0da.png">
<img width="450" alt="Screen Shot 2019-07-17 at 1 22 15 PM" src="https://user-images.githubusercontent.com/3083452/61372348-28d3ad80-a897-11e9-9622-f6f8f1e8de2c.png">
<img width="534" alt="Screen Shot 2019-07-17 at 1 22 37 PM" src="https://user-images.githubusercontent.com/3083452/61372355-2b360780-a897-11e9-9647-2482e79e8fb7.png">

**Comment by nathangibson** [comment]
See also: https://github.com/usaybia/usaybia-data/wiki/Transcription-of-Sources-from-Page-Images#cleaning-up-the-layout
