### ISSUE TITLE
Questions about occup. descriptors and place

### ISSUE THREAD

**Issue by MalindaT** [usaybia/usaybia-data#8]
Dear all, 

I dont know how to tag the ابي or ابيه. It is often listed, and I dont know if all of them are named or just persons without a specific name. Same goes fot عمي which I tagged as occup. so far.

Also there is the باب الفراديس which I can not tag, beacause the system doesnt find it. (must be one of the old gate in damascus?)

**Comment by nathangibson** [comment]
@MalindaT Thanks for the question. 

The tags listed for Step 2 here https://github.com/usaybia/usaybia-data/wiki/Using-Recogito are not ones you have to do. You can if you want, but I will also be looking for these as I go back through the text myself.

If you do tag these:
- For ابيه and عمي please use "relational-descriptor" (not "occupational-descriptor"). It's okay to tag these even if the person is not named.
- Don't tag ابو/ابي as a relational-descriptor when it's part of someone's name. These were sometimes titles instead of a literal relationship. 

As far as places, you can actually tag any place even if it is not in the system. Just highlight the word and click "Place" and then "OK," without doing the search process. Later we can add our own identification for the place.
